dataagg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('youtube/',include('youtubeapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtubeapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from . views import *
from . import views
from rest_framework_swagger.views import get_swagger_view
from . charts import *
from . data_req import *
schema_view = get_swagger_view(title='YouMarket Youtube Data Aggregator API')
router = routers.DefaultRouter()
router.register(r'ChannelMasterViewSet', views.ChannelMasterViewSet, base_name='ChannelMaster')
router.register(r'ChannelStatsViewSet',views.ChannelStatsViewSet,base_name='ChannelStats')
router.register(r'VideoMasterViewSet',views.VideoMasterViewSet,base_name='VideoMaster')
router.register(r'VideoStatsViewSet',views.VideoStatsViewSet,base_name='VideoStats')

app_name="youtubeapp"

urlpatterns = [
    url(r'^$', schema_view),
    url('home',views.home,name='home'), #home page url
    url('vidstatsplot',vidstatsplot,name="vidstatsplot"), #individual vid stats displayed by MatPlotLib
    url('chanstatplot',chanstatplot,name="chanstatplot"), #individual Channel stats displayed by MatPlotLib
    url('getvideostatsui',views.getvideostatsui,name="getvideostatsui"),# Individual Vid Stats UI
    url('getchannelmasterui',views.getchannelmasterui,name='getchannelmasterui'),# Individual Channel Stats UI
    url('getvideomasterui',views.getvideomasterui,name='getvideomasterui'),# Individual Vid Master details UI
    url('getchannelstatsui',views.getchannelstatsui,name='getchannelstatsui'),# Individual Channel  Stats UI
    url('api/', include(router.urls)), #API root
]

youtubeapp/models.py
from django.db import models


class ChannelMaster(models.Model):
    """contains the Master data of the channels"""
    channel_id=models.CharField(default=None,max_length=200)
    channel_name=models.CharField(default=None,max_length=200)
    description=models.TextField(default='entertainment')
    def __str__(self):
        return self.channel_name

class ChannelStats(models.Model):
    """Model contains the Stats of each individual channel with ChannelMaster as Foreign Key"""
    channel_master = models.ForeignKey('ChannelMaster', on_delete=models.CASCADE)
    total_views=models.BigIntegerField(default=None)
    subscriber_count=models.BigIntegerField(default=None)
    time_stamp=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.channel_master.channel_name
    def __unicode__(self):
        return self.channel_master.channel_name

class VideoMaster(models.Model):
    """Model contains videos from all the available channels with Channelmaster as FK"""
    channel_master = models.ForeignKey('ChannelMaster', on_delete=models.CASCADE)
    video_id=models.CharField(default=None,max_length=200)
    video_name=models.CharField(default=None,max_length=200)
    def __str__(self):
        return self.video_name
    def __unicode__(self):
        return self.video_name

class VideoStats(models.Model):
    """Model Contains the details of the individual videos across channels with VideoMaster as Fk"""
    video_master = models.ForeignKey('VideoMaster', on_delete=models.CASCADE)
    total_views=models.BigIntegerField(default=None)
    like_count=models.BigIntegerField(default=None)
    dislike_count=models.BigIntegerField(default=None)
    comment_count=models.BigIntegerField(default=None)
    time_stamp=models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.video_master.video_name)
    def __unicode__(self):
        return str(self.video_master.video_name)

youtubeapp/views.py
# Import the modules
import requests
import json
from rest_framework import serializers, viewsets
from . serializer import *
from . models import *
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from django.views.decorators.cache import cache_page
from . filters import *
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
import matplotlib
import matplotlib.pyplot as plt

""" 
View contains the Serializer viewsets and the generic views for the loading the template in frontend
"""

""" Serializer Viewset """
class ChannelMasterViewSet(viewsets.ModelViewSet):
    serializer_class = ChannelMasterSerializer
    queryset = ChannelMaster.objects.all()
    # filter_backends = (DjangoFilterBackend,)
    # filterset_fields = ('@channel_id', '@channel_name')
    filter_backends = (filters.SearchFilter,)
    search_fields = ('channel_id', 'channel_name')

class ChannelStatsViewSet(viewsets.ModelViewSet):
    serializer_class = ChannelStatsSerializer
    queryset = ChannelStats.objects.all()

class VideoMasterViewSet(viewsets.ModelViewSet):
    serializer_class = VideoMasterSerializer
    queryset = VideoMaster.objects.all()
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = ('video_id', 'video_name')

class VideoStatsViewSet(viewsets.ModelViewSet):
    serializer_class = VideoStatsSerializer
    queryset = VideoStats.objects.all()


""" Regular Views for Template loading """
def home(request):
    """Home Page-contains the links for various pages of the Application"""
    return render(request,"youtubeapp/home.html")

def getchannelmasterui(request):
    """Contains the Master data of the Channel like the id , name , description"""
    return render(request,"youtubeapp/index.html")

def getvideomasterui(request):
    """Contains the Details of all the available videos from Various Channels"""
    return render(request,"youtubeapp/video_master.html")

def getchannelstatsui(request):
    """Contains the Various stats of the Channel master data"""
    return render(request,"youtubeapp/channel_stats.html")

def getvideostatsui(request):
    """contains the details og the individual video stats for videos across all the available channels"""
    return render(request,"youtubeapp/video_stats.html")

youtubeapp/templates/youtubeapp/channel_stats.html
<html>
<head>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<center><h2>Enter the Channel Id to get the statistics</h2></center>
    <br><br>
<center>
   <form type="get" action="{%url 'youtubeapp:chanstatplot' %}" style="margin: 0">
    <input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
       <button id="search_submit" type="submit" >Submit</button>
   </form>
    </center>
<center><h3 style="padding-top:30px;"><u>Channels Statistics<u></h3></center>
<div class="container" style="padding-right:50px;">
<div id="myGrid" style="height: 250px; width:900px;" class="ag-theme-balham"></div>
</div>

<script type="text/javascript" charset="utf-8">
    const columnDefs = [
        {headerName: "channel_master", field: "channel_master", sortable: true},
        {headerName: "total_views", field: "total_views", sortable: true,filter: true},
        {headerName: "time_stamp", field: "time_stamp", sortable: true,filter: true},
        {headerName: "subscriber_count", field: "subscriber_count", sortable: true,filter: true},
    ];
    const gridOptions = {
        columnDefs: columnDefs,
        <!--enableSorting: true,-->
        <!--enableFilter: true-->
    };
    const eGridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(eGridDiv, gridOptions);
    fetch('http://127.0.0.1:8000/youtube/api/ChannelStatsViewSet/').then(function (response) {
        return response.json();
    }).then(function (data) {
    console.log(data);
        gridOptions.api.setRowData(data);
    })
</script>
</body>

youtubeapp/templates/youtubeapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Youtube Data Aggregator</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>
<style>
  html, body { height: 100%; padding: 0; margin: 0; }
div { width: 50%; height: 50%; float: left; }
#div1 { background: #DDD; }
#div2 { background: #AAA; }
#div3 { background: #777; }
#div4 { background: #444; }
.w3-button {width:150px;}

</style>

<div id="div1" style="text-align:center;">
  <h1>Channel Master Data</h1>
  <a href="#"  onclick='window.open("http://127.0.0.1:8000/youtube/getchannelmasterui");return false;' ><button>Channel Master data</button></a>
</div>
<div id="div2" style="text-align:center;">
  <h1>Channel Statistics</h1>
  <a href="#"  onclick='window.open("http://127.0.0.1:8000/youtube/getchannelstatsui");return false;' ><button>Channel Statistics</button></a>
</div>
<div id="div3" style="text-align:center;">
  <h1>Video Master Data</h1>
  <a href="#"  onclick='window.open("http://127.0.0.1:8000/youtube/getvideomasterui");return false;' ><button>Video Master Data</button></a>
</div>
<div id="div4" style="text-align:center;">
  <h1>Video Statistics</h1>
  <button><a href="#"  onclick='window.open("http://127.0.0.1:8000/youtube/getvideostatsui");return false;' >Video Statistics</a></button></a>
</div>


</body>
</html>

youtubeapp/templates/youtubeapp/index.html
<html>
<head>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<center><h3 style="padding-top:30px;"><u>Channels Data<u></h3></center>
<div class="container" style="padding-right:50px;">
<div id="myGrid" style="height: 250px; width:900px;" class="ag-theme-balham"></div>
</div>

<script type="text/javascript" charset="utf-8">
    const columnDefs = [
        {headerName: "channel_id", field: "channel_id", sortable: true},
        {headerName: "channel_name", field: "channel_name", sortable: true,filter: true},
        {headername: "description",field:"description"}
    ];
    const gridOptions = {
        columnDefs: columnDefs,
        <!--enableSorting: true,-->
        <!--enableFilter: true-->
    };
    const eGridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(eGridDiv, gridOptions);
    fetch('http://127.0.0.1:8000/youtube/api/ChannelMasterViewSet/').then(function (response) {
        return response.json();
    }).then(function (data) {
    console.log(data);
        gridOptions.api.setRowData(data);
    })
</script>
</body>

youtubeapp/templates/youtubeapp/video_master.html
<html>
<head>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<center><h3 style="padding-top:30px;"><u>Video Details<u></h3></center>
<div class="container" style="padding-right:50px;">
<div id="myGrid" style="height: 250px; width:900px;" class="ag-theme-balham"></div>
</div>


<script type="text/javascript" charset="utf-8">
    const columnDefs = [
        {headerName: "channel_master", field: "channel_master", sortable: true},
        {headerName: "video_id", field: "video_id", sortable: true,filter: true},
        {headerName: "video_name", field: "video_name", sortable: true,filter: true},
    ];
    const gridOptions = {
        columnDefs: columnDefs,
        <!--enableSorting: true,-->
        <!--enableFilter: true-->
    };
    const eGridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(eGridDiv, gridOptions);
    fetch('http://127.0.0.1:8000/youtube/api/VideoMasterViewSet/').then(function (response) {
        return response.json();
    }).then(function (data) {
    console.log(data);
        gridOptions.api.setRowData(data);
    })
</script>

</body>

youtubeapp/templates/youtubeapp/video_stats.html
<html>
<head>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<center>
<center></center><h2>Enter the Video Id to get the statistics</h2>
   <form type="get" action="{%url 'youtubeapp:vidstatsplot' %}" style="margin: 0">
    <input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
    <button id="search_submit" type="submit" >Submit</button>

   </form>

</center>
<center><h3 style="padding-top:30px;"><u>Video Statistics<u></h3></center>
<div class="container" style="padding-right:50px;">
<div id="myGrid" style="height: 250px; width:900px;" class="ag-theme-balham"></div>
</div>

<script type="text/javascript" charset="utf-8">
 console.log("This is america");
    const columnDefs = [
        {headerName: "video_master", field: "video_master", sortable: true},
        {headerName: "total_views", field: "total_views", sortable: true,filter: true},
        {headerName: "time_stamp", field: "time_stamp", sortable: true,filter: true},
        {headerName:"like_count",field:"like_count",sortable:true},
        {headerName:"dislike_count",field:"dislike_count",sortable:true},
        {headerName:"comment_count",field:"comment_count",sortable:true},

    ];
    const gridOptions = {
        columnDefs: columnDefs,
        <!--enableSorting: true,-->
        <!--enableFilter: true-->
    };
    const eGridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(eGridDiv, gridOptions);
    fetch('http://127.0.0.1:8000/youtube/api/VideoStatsViewSet/').then(function (response) {
        return response.json();
    }).then(function (data) {

        console.log(data[0]['video_master']['video_name']);

        gridOptions.api.setRowData(data);
    })
</script>

</body>